### ISSUE TITLE
Fix transform

### ISSUE THREAD

**Issue by MarcusJoh** [MarcusJoh/Grupppro#1]
`
<h1>hej</h1>

`

**Comment by MarcusJoh** [comment]
https://github.com/MarcusJoh/Grupppro/blob/f3665f433ce9f320c236c6d7f94e249adab68074/index.html#L15

**Comment by spajk00** [comment]
Fixed

**Comment by spajk00** [comment]
Ok

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
